---
- name: Install and configure Nginx
  hosts: web
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Ensure Nginx service is enabled and started
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create index.html file with custom message
      template:
        src: ./index.html.j2
        dest: /usr/share/nginx/html/index.html
